# Generated by Django 5.2.7 on 2025-12-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
