# Generated by Django 5.2.7 on 2025-12-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_remove_event_participants_participant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
