# Generated by Django 5.2.7 on 2025-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_delete_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="participants", to="event.event"
                    ),
                ),
            ],
        ),
    ]
