# Generated by Django 5.2.7 on 2025-12-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_participant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="last_name",
        ),
    ]
