# Generated by Django 5.2.7 on 2025-12-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_rename_first_name_participant_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="events",
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="event.participant"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="event.category",
            ),
        ),
    ]
