# Generated by Django 5.2.7 on 2025-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_alter_event_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
