# Generated by Django 5.2.7 on 2025-12-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_rename_name_participant_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
    ]
