# Generated by Django 5.2.7 on 2025-12-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0013_event_participants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
