# Generated by Django 5.2.7 on 2025-12-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0014_delete_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="event_asset"),
        ),
    ]
