# Generated by Django 5.2.7 on 2025-12-06 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_event_img"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                default="event_asset/default.jpg",
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
